[workspace]
resolver = "2"
members = [
    "libtashkeel_base",
    "libtashkeel",
    "libtashkeel-wasm",
    "pylibtashkeel",
    "tashkeel",
]

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1

[profile.release.package.libtashkeel-wasm]
opt-level = "s"
